SRC = src/main.c \
src/addBookInDataBase.c \
src/deleteBooks.c \
src/headMessage.c \
src/init.c \
src/isValidDate.c \
src/isFileExists.c \
src/isNameValid.c \
src/menu.c \
src/printMessageCenter.c \
src/searchBooks.c \
src/updateCredential.c \
src/viewBooks.c \
src/welcomeMessage.c \
src/login.c 

INC = inc

target : $(SRC)
	gcc $^ -I$(INC) -o $@